//@version=5

strategy(title = "CCI - Strategy", initial_capital= 10000, calc_on_every_tick = true)

length = input.int(50, minval=1)
stop_multiplier = input.float(2, minval=0.1, title="Stop Multiplier")
equity_reinvest = input.bool(false, title = "Equity Reinvest")


enable_long = input.bool(true, title = "Enable Long")
enable_short = input.bool(false, title = "Enable Short")

enable_smoothing = input.bool(false, title = "Enable CCI smoothing")
cci_smoothing = input.int(4, minval=1, title = "CCI smoothing")

cash = if equity_reinvest
    strategy.equity
else
    strategy.initial_capital

start_year = input.int(2015, title = "Start Year")

high_line = input.int(100, maxval=300, title="High Line")
low_line = input.int(-100, minval=-300, title="Low Line")


cci_color = input(#b1b1b1, "Trade Line", group="Color Settings", inline="Signal")
bull_color = input.color(#007906ab, "Buy", inline = "1")
bull_color2 = input.color(#82cd86be, "Buy", inline = "1")
bear_color = input.color(#ff5100c7, "Sell", inline = "1")
bear_color2 = input.color(#ff9d6fc7, "Sell", inline = "1")
no_color = color(na)


typeMA = input.string(title = "Method", defval = "SMA", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="Smoothing")
smoothingLength = input.int(title = "Length", defval = 5, minval = 1, maxval = 100, group="Smoothing")

ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)




// Heikin-Ashi
heikinashi = ticker.heikinashi(syminfo.tickerid)
heikinashi_open = request.security(heikinashi, timeframe.period, open)
heikinashi_close = request.security(heikinashi, timeframe.period, close)
heikinashi_high = request.security(heikinashi, timeframe.period, high)
heikinashi_low = request.security(heikinashi, timeframe.period, low)
heikinashi_hlc3 = request.security(heikinashi, timeframe.period, hlc3)

// CCI
ma = ta.sma(heikinashi_hlc3, length)
cci = (heikinashi_hlc3 - ma) / (0.015 * ta.dev(heikinashi_hlc3, length))

cci_line_color = if cci < 100 and cci > -100
    cci_color
else
    #2962FF

if enable_smoothing
    cci := ta.sma(cci, cci_smoothing)

plot(cci, "CCI", color=cci_line_color, linewidth=2)

band1 = hline(high_line, "Upper Band", color=#787B86, linestyle=hline.style_dotted)
hline(0, "Middle Band", color=color.new(#787B86, 50))
band0 = hline(low_line, "Lower Band", color=#787B86, linestyle=hline.style_dotted)
fill(band1, band0, color=color.rgb(33, 150, 243, 90), title="Background")

smoothingLine = ma(cci, smoothingLength, typeMA)
plot(smoothingLine, title="Smoothing Line", color=#f37f20, display=display.none)

long_signal_num = 0
long_signal_num := long_signal_num[1]
short_signal_num = 0
short_signal_num := short_signal_num[1]

opentrades = strategy.opentrades.size(strategy.opentrades - 1)

the_bg = if cci[1] > high_line and cci < high_line
    long_signal_num := 0
    short_signal_num += 1
    // strategy.cancel_all()
    strategy.close("long", comment = "close long")
    if start_year <= year(time_tradingday) and enable_short and opentrades >= 0
        strategy.entry("short", strategy.short, cash/open)
        strategy.exit("STOP short", "short", loss = open*stop_multiplier)
    if cci[2] > high_line or short_signal_num >= 3
        bear_color
    else
        bear_color2
else if cci[1] < low_line and cci > low_line
    short_signal_num := 0
    long_signal_num += 1
    // strategy.cancel_all()
    strategy.close("short", comment = "close short")
    if start_year <= year(time_tradingday) and enable_long and opentrades <= 0
        strategy.entry("long", strategy.long, cash/open)
        strategy.exit("STOP long", "long", loss = open*stop_multiplier)
    if cci[2] < low_line or long_signal_num >= 3
        bull_color
    else
        bull_color2
else
    no_color

bgcolor(the_bg)
