//@version=5
strategy(title = "ROC - Strategy", initial_capital= 10000, calc_on_every_tick = true)

length = input.int(9, minval=1, title = "Length")

stop_multiplier = input.float(2, minval=0.1, title="Stop Multiplier")
equity_reinvest = input.bool(false, title = "Equity Reinvest")

hline(0, color=#787B86, title="Zero Line")

// Heikin-Ashi
ha = ticker.heikinashi(syminfo.tickerid)
[ha_open, ha_close, ha_high, ha_low, ha_hlc3] = request.security(heikinashi, timeframe.period, [open, close, high, low, hlc3])


roc = 100 * (ha_close - ha_close[length])/ha_close[length]
rocPlot = plot(roc, color=#2962FF, title="ROC - TEST")

cash = if equity_reinvest
    strategy.equity
else
    strategy.initial_capital

if roc < 0
    strategy.entry("short", strategy.short, cash/open)
    strategy.exit("STOP short", "short", loss = open*stop_multiplier)
if roc > 0
    strategy.entry("long", strategy.long, cash/open)
    strategy.exit("STOP long", "long", loss = open*stop_multiplier)