//@version=5

strategy(title = "CCI - Just Long - Strategy", initial_capital= 10000, calc_on_every_tick = true, use_bar_magnifier = false)

length = input.int(50, minval=1)
stop_multiplier = input.float(2, minval=0.1, title="Stop Multiplier")
equity_reinvest = input.bool(false, title = "Equity Reinvest")
short_enabled = input.bool(false, title = "Enable Shorting")
normal_hours = input.bool(false, title = "Normal Hours Only")

enable_roc_close = input.bool(true, title = "Enable ROC close")
roc_close = input.float(0.15, title="ROC close")
roc_length = input.int(18, minval=1, title="ROC length")


cash = if equity_reinvest
    strategy.equity
else
    strategy.initial_capital

start_year = input.int(2015, title = "Start Year")

high_line = input.int(100, maxval=300, title="High Line")
low_line = input.int(-100, minval=-300, title="Low Line")

cci_color = #b1b1b1
bull_color = #007906ab
bull_color2 = #82cd86be
bear_color = #ff5100c7
bear_color2 = #ff9d6fc7
no_color = color(na)

enable_weak_sig_buy = input.bool(true, title = "Enable Weak Signal Buy")

order_divisor = input.int(1, minval=1, title="Order divisor")

// typeMA = input.string(title = "Method", defval = "SMA", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"], group="Smoothing")
// smoothingLength = input.int(title = "Length", defval = 5, minval = 1, maxval = 100, group="Smoothing")

ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)


// Heikin-Ashi
heikinashi = ticker.heikinashi(syminfo.tickerid)
[ha_open, ha_close, ha_high, ha_low, ha_hlc3] = request.security(heikinashi, timeframe.period, [open, close, high, low, hlc3])

opentrades = strategy.opentrades.size(strategy.opentrades - 1)

// CCI
ma = ta.sma(ha_hlc3, length)
cci = (ha_hlc3 - ma) / (0.015 * ta.dev(ha_hlc3, length))

cci_line_color = if cci < 100 and cci > -100
    cci_color
else
    #2962FF

plot(cci, "CCI", color=cci_line_color, linewidth=2)

band1 = hline(high_line, "Upper Band", color=#787B86, linestyle=hline.style_dotted)
hline(0, "Middle Band", color=color.new(#787B86, 50))
band0 = hline(low_line, "Lower Band", color=#787B86, linestyle=hline.style_dotted)
fill(band1, band0, color=color.rgb(33, 150, 243, 90), title="Background")

// smoothingLine = ma(cci, smoothingLength, typeMA)
// plot(smoothingLine, title="Smoothing Line", color=#f37f20, display=display.none)

// ROC
roc = 100 * (ha_close - ha_close[roc_length])/ha_close[roc_length]

// Signals
varip int long_signal_num = 0
varip int long_signal_num_weak = 0
varip int short_signal_num = 0
varip int short_signal_num_weak = 0

the_bg = if cci[1] > high_line and cci < high_line
    if cci[2] > high_line
        long_signal_num := 0
        long_signal_num_weak := 0
        short_signal_num += 1
        bear_color
    else
        short_signal_num_weak += 1
        bear_color2
else if cci[1] < low_line and cci > low_line
    if cci[2] < low_line
        short_signal_num := 0
        short_signal_num_weak := 0
        long_signal_num += 1
        bull_color
    else
        long_signal_num_weak += 1
        bull_color2
else
    no_color

bgcolor(the_bg)

time_signal = not normal_hours or not na(time(timeframe.period, "0930-1550"))
// time_signal_sell = normal_hours and not na(time(timeframe.period, "1555-1600"))

// Buy / Sell
long = false
short = false
close_it = false

if time_signal
    if long_signal_num > long_signal_num[1] and start_year <= year(time_tradingday) 
        long := true
    else if long_signal_num_weak > long_signal_num_weak[1] and start_year <= year(time_tradingday) and enable_weak_sig_buy
        long := true
    else if short_signal_num > 0
        if enable_roc_close 
            if roc <= roc_close and roc[1] > 0
                close_it := true
        else
            close_it := true

    if close_it
        strategy.close("long", comment = "close long")
        short := true

    if short_signal_num > short_signal_num[0] 
        short := true
    else if short_signal_num_weak > short_signal_num_weak[0] 
        short := true

if long
    strategy.close("short", comment = "close short")    
    strategy.entry("long", strategy.long, cash/open/order_divisor)
    strategy.exit("STOP long", "long", loss = open*stop_multiplier)
else if short and short_enabled 
    strategy.entry("short", strategy.short, cash/open/order_divisor)
    strategy.exit("STOP short", "short", loss = open*stop_multiplier)

// if time_signal_sell
//     strategy.close("long", comment = "close long")
//     strategy.close("short", comment = "close short")

