//@version=5
indicator(title="ATR Percentage Multiplier", shorttitle="ATR%M", overlay=false, timeframe="", timeframe_gaps=true)
length = input.int(title="Length", defval=14, minval=1)
smoothing = input.string(title="Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA"])
multiplier = input.int(title="Multiplier", defval=50, minval=1)
ma_function(source, length) =>
	switch smoothing
		"RMA" => ta.rma(source, length) / open * multiplier * 100
		"SMA" => ta.sma(source, length) / open * multiplier * 100
		"EMA" => ta.ema(source, length) / open * multiplier * 100
		=> ta.wma(source, length)  / open * multiplier * 100
plot(ma_function(ta.tr(true), length), title = "ATR%", color=color.new(#B71C1C, 0))